# Generated by Django 3.2 on 2022-04-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_has_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_quality',
        ),
    ]
